"""add needs_revision status, textbook_page canvas owner, textbook page annotations

Revision ID: a05529fdc405
Revises: dae9e4511c6b
Create Date: 2026-07-19 19:20:02.225785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05529fdc405'
down_revision = 'dae9e4511c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('textbook_page_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('canvas_document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_document_id'], ['canvas_documents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbooks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('textbook_id', 'student_id', 'page_number', name='uq_textbook_page_annotation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('textbook_page_annotations')
    # ### end Alembic commands ###
