"""Add textbook publish workflow

Revision ID: e8f76534cfd4
Revises: d732e030aa06
Create Date: 2026-07-18 18:34:44.807870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f76534cfd4'
down_revision = 'd732e030aa06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('textbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('textbooks', schema=None) as batch_op:
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###
